.gitignore, templates/geosafe/0/docker-compose.yml, templates/geosafe/0/rancher-compose.yml
Properly put prefix and suffix for SITEURL
=> Modify settings/environment variable generations.

templates/realtime/1/docker-compose.yml, templates/realtime/1/rancher-compose.yml, templates/realtime/config.yml
WIP.
Will experiment with conditional input.
Bump version with legacy InaSAFE Realtime v3.5
=> InaSAFE Realtime v3.5 release

templates/realtime/1/docker-compose.yml, templates/realtime/1/rancher-compose.yml
Additional variables in rancher-compose:
- REST Credentials
- Sync Device Prefix
- SFTP Expose Port
=> [Realtime] Add options for REST Credentials

templates/realtime/0/rancher-compose.yml, templates/realtime/1/docker-compose.yml, templates/realtime/1/rancher-compose.yml
Changes:
- Slimming down unnecessary btsync container
- Use conditional switch for volume backends options
- Optional sync containers
- Readable compose version
=> [Realtime] Add more catalog option

templates/geosafe/1/docker-compose.yml, templates/geosafe/1/rancher-compose.yml
add catalogue for:
- geosafe
- geonode
=> add geosafe rancher catalogue for testing

templates/geonode/1/docker-compose.yml, templates/geonode/1/rancher-compose.yml, templates/geonode/config.yml
- Improvements on healthcheck
- Exports port using Rancher LB Service
=> [GeoNode_QGIS-Server] Release new stable version (2.7.6)

templates/realtime/2/docker-compose.yml.tpl, templates/realtime/2/rancher-compose.yml, templates/realtime/config.yml
Pin stable docker image version
=> [realtime] Pin image version

templates/k-bims-ledet/0/docker-compose.yml, templates/k-bims-ledet/0/rancher-compose.yml
- Improve nginx conf loading
- Slight change in nginx config for uwsgi (domain name)
- Add new rancher question
=> [LEDET-BIMS] Rancher catalogue update

templates/geosafe/1/docker-compose.yml, templates/geosafe/1/rancher-compose.yml, templates/geosafe/config.yml
[WIP] Update catalog and add more options.
=> [GeoSAFE] Update catalog

templates/realtime/0/rancher-compose.yml, templates/realtime/1/docker-compose.yml, templates/realtime/1/rancher-compose.yml, templates/realtime/2/docker-compose.yml.tpl, templates/realtime/2/rancher-compose.yml, templates/realtime/config.yml
Synchronize changes with master.
=> [realtime] Synchronize with master

templates/kobotoolbox/0/docker-compose.yml, templates/kobotoolbox/0/rancher-compose.yml, templates/kobotoolbox/config.yml
Refactored Volume declaration and scripts.
=> [kobotoolbox] Initial version

templates/kobotoolbox/0/docker-compose.yml, templates/kobotoolbox/0/rancher-compose.yml
=> [kobotoolbox] add task timeout

templates/scanwebgis/0/docker-compose.yml, templates/scanwebgis/0/rancher-compose.yml
Add database settings for Scanwebgis
=> [scanwebgis] Add database settings for Scanwebgis

templates/geonode/2/docker-compose.yml, templates/geonode/2/rancher-compose.yml, templates/geosafe/1/docker-compose.yml, templates/geosafe/1/rancher-compose.yml
=> [GeoSAFE] Add theme app support

templates/geosafe/1/docker-compose.yml, templates/geosafe/1/rancher-compose.yml
For Registration confirmation, invitation, and many other.
Related with kartoza/docker-geosafe#36
=> [GeoSAFE] Include email settings

templates/kobotoolbox/0/docker-compose.yml, templates/kobotoolbox/0/rancher-compose.yml
- Add local SMTP settings for testing server (thru options of using External SMTP server or not)
- Fixed nginx settings to http, because it is better to terminate SSL from Rancher LB
=> [kobotoolbox] Production improvements

templates/geosafe/1/docker-compose.yml
This allow celery to install custom skin app (for Headless report template)
=> [geosafe] Add initializations for celery

templates/scanagroempresa/0/docker-compose.yml
WIP
Wait until docker images accomodate these.
=> [scanagroempresa] Add service for updating kobo/geonode layer caches

templates/kobotoolbox/1/docker-compose.yml, templates/kobotoolbox/1/rancher-compose.yml
add custom kobocat and kpi theme into rancher's orchestration
=> add custom theme into orchestration

templates/scanagroempresa/0/docker-compose.yml
It was tested on server that the script is able to handle https redirection correctly now.
=> [scanagroempresa] Revert back GeoServer connection to use public for SAE

templates/scanagroempresa/0/docker-compose.yml, templates/scanagroempresa/0/rancher-compose.yml
Include internal SMTP server to send email
=> [scanagroempresa] Add Email SMTP settings

templates/scanagroempresa/0/docker-compose.yml
Tobe merged after tested in testing.
=> [scanagroempresa] Add GeoNode public url for scanagroempresa

templates/scanagroempresa/0/docker-compose.yml
To be merged after testing in server
=> [scanagroempresa] Add geonode-updatelayers service

templates/kobotoolbox/0/docker-compose.yml, templates/kobotoolbox/0/rancher-compose.yml
It's working!
Borg now chained with service backups
=> Kobotoolbox

templates/scanagroempresa/0/docker-compose.yml, templates/scanagroempresa/0/rancher-compose.yml
Related with: https://github.com/kartoza/scanagroempresa-docker/pull/32 and https://github.com/kartoza/scanagroempresa/pull/453
=> [scanagroempresa] Add settings for GeoNode Index URL Prefix

templates/scanagroempresa/0/docker-compose.yml, templates/scanagroempresa/0/rancher-compose.yml
Include GeoNode credentials for kobo-geonode sync service.
=> [scanagroempresa] Add GeoNode credentials for kobo-geonode sync service

templates/kobotoolbox/0/docker-compose.yml
Use `kartoza/postgis` for SSL support
=> [kobotoolbox] Use kartoza/postgis for database

templates/scanagroempresa/0/docker-compose.yml
Related with issue: https://github.com/kartoza/scanagroempresa/issues/408
That features needs celery as worker to work reliably.
=> [scanagroempresa] Add celery worker

templates/ford3/0/docker-compose.yml, templates/ford3/0/rancher-compose.yml, templates/ford3/config.yml
Minimal orchestration of Ford3
=> [ford3] Initial commit for Ford3 template

templates/scanagroempresa/0/docker-compose.yml
=> [scanagroempresa][release] v1.0.6-20190425

templates/kobotoolbox/0/docker-compose.yml, templates/kobotoolbox/0/rancher-compose.yml
Add options in order to specify strong password
=> [kobotoolbox] Add options to specify postgres password

templates/scanagroempresa/0/docker-compose.yml
Use kartoza/scanagroempresa_geonode_generic:2.9-dev-geonode_generic-20190425 image
=> [scanagroempresa] Update geonode image to 20190425

templates/scanagroempresa/0/docker-compose.yml
We need a volume to store the private key.
=>  [scanagroempresa] Add volumes to store ssh access key for private theme

templates/realtime/2/docker-compose.yml, templates/realtime/2/rancher-compose.yml, templates/realtime/config.yml
=> [realtime] Minor fix release update: v4.0.1-18.08.21
